apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: {{ include "airflow.fullname" . }}-worker
  labels:
    app.kubernetes.io/name: {{ include "airflow.name" . }}-worker
    helm.sh/chart: {{ include "airflow.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  #replicas: {{ .Values.replicaCount }}
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "airflow.name" . }}-worker
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "airflow.name" . }}-worker
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.airflow.image.repository }}:{{ .Values.airflow.image.tag }}"
          imagePullPolicy: {{ .Values.airflow.image.pullPolicy }}
          #envFrom:
          #  - configMapRef:
          #      name: "{{ template "airflow.fullname" . }}-env"
          #env:
          #  - name: POSTGRES_USER
          #    valueFrom:
          #      secretKeyRef:
          #        name: {{ template "airflow.fullname" . }}
          #        key: postgresUsername
          env:
            - name: LOAD_EX
              value: "y"
            - name: EXECUTOR
              value: Celery
            - name: FERNET_KEY
              value: {{ .Values.airflow.fernetKey }}
            - name: POSTGRES_USER
              value: {{ .Values.postgresql.postgresqlUsername }}
            - name: POSTGRES_PASSWORD
              value: {{ .Values.postgresql.postgresqlPassword }}
            - name: POSTGRES_DB
              value: {{ .Values.postgresql.postgresqlDatabase }}
            - name: POSTGRES_HOST
              value: "{{ template "airflow.postgresql.fullname" . }}"
            - name: POSTGRES_PORT
              value: "{{ .Values.postgresql.servicePort }}"
            - name: REDIS_HOST
              value: "{{ template "airflow.redis.fullname" .}}"
            - name: REDIS_PORT
              value: "6379"
            - name: REDIS_PASSWORD
              value: "redispass"
          args:
            - "bash"
            - "-c"
            - >
              airflow worker
          volumeMounts:
            - name: dags
              mountPath: {{ .Values.airflow.dagsPath }}
            - name: logs
              mountPath: {{ .Values.airflow.logsPath }}
          resources:
{{ toYaml .Values.resources | indent 12 }}
    {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
      volumes:
        - name: dags
          persistentVolumeClaim:
            claimName: dags
        - name: logs
          persistentVolumeClaim:
            claimName: logs