# Dags
apiVersion: v1
kind: PersistentVolume
metadata:
  name: dags
  labels:
    app: {{ template "airflow.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  capacity:
    storage: 100M
  accessModes:
    - ReadWriteMany
  storageClassName: standard
  hostPath:
    path: "/data/dags/"
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: dags
  labels:
    app: {{ template "airflow.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100M
  volumeName: dags
---
#Logs
apiVersion: v1
kind: PersistentVolume
metadata:
  name: logs
  labels:
    app: {{ template "airflow.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  capacity:
    storage: 100M
  accessModes:
    - ReadWriteMany
  storageClassName: standard
  hostPath:
    path: "/data/logs/"
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: logs
  labels:
    app: {{ template "airflow.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100M
  volumeName: logs
