dependencies:
- name: postgresql
  version: 6.3.12
  repository: https://kubernetes-charts.storage.googleapis.com/
- name: redis
  version: 9.2.2
  repository: https://kubernetes-charts.storage.googleapis.com/
